---
title: Lecture 5
subtitle: R Basics; Descriptive Statistics
format:
  clean-revealjs:
    self-contained: false
    chalkboard: true
    incremental: true
    code-annotations: hover
    scrollable: false

    # logo: logo-title-slide.png
author:
  - name: Byeong-Hak Choe
    email: bchoe@geneseo.edu
    affiliations: SUNY Geneseo
date: 2024-09-10
execute: 
  eval: true
  echo: false
callout-icon: false

from: markdown+emoji
include-after-body: target-hover.html # effect.html

# bibliography: refs.bib
---


```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)


theme_set(theme_fivethirtyeight()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.5),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 0,
                               size = rel(1.5),
                               margin = margin(0,10,0,0)),
                axis.text.x = element_text(size = rel(1.5)),
                axis.text.y = element_text(size = rel(1.5)),
                strip.text = element_text(size = rel(1.5)),
                legend.position = "top",
                legend.text = element_text(size = rel(1.5)),
                legend.title = element_text(size = rel(1.5))
                )
          )
```



## R Basics
### Workflow: Quotation marks, parentheses, and `+`

```{.r}
x <- "hello
```


- Quotation marks and parentheses must always come in a pair.
  - If not, Console Pane will show you the continuation character `+`:
  
- The `+` tells you that R is waiting for more input; it doesn’t think you’re done yet. 





## R Basics
### Functions

- A function can take any number and type of input *parameters* and **return** any number and type of output *results*.

- R ships a vast number of built-in functions. 

- R also allows a user to define a new function.

- We will mostly use built-in functions.



## R Basics
### Functions, Arguments, and Parameters

```{.r}
library(tidyverse)

# The function `str_c()`, provided by `tidyverse`, concatenates characters.
str_c("Data", "Analytics")
str_c("Data", "Analytics", sep = "!")
```


- We invoke a function by entering its name and a pair of opening and closing parentheses. 

- Much as a cooking recipe can accept ingredients, a function invocation can accept inputs called **arguments**. 

- We pass arguments sequentially inside the parentheses (, separated by commas).

- A **parameter** is a name given to an expected function argument.

- A *default argument* is a fallback value that R passes to a parameter if the function invocation does not explicitly provide one.



## R Basics
### Arithmetic Operations and Mathematical Functions

::: {.nonincremental}
::: {.panel-tabset}

## Algebra

:::: {.columns}
::: {.column width="50%"}
```{.r}
5 + 3
5 - 3
5 * 3
5 / 3
5^3
```
:::

::: {.column width="50%"}
```{.r}
( 3 + 4 )^2
3 + 4^2
3 + 2 * 4^2
3 + 2 * 4 + 2
(3 + 2) * (4 + 2)
```
:::

::::

- All of the basic operators with parentheses we see in mathematics are available to use.

- R can be used for a wide range of mathematical calculations.


## Math functions



:::: {.columns}

::: {.column width="50%"}
```{.r}
5 * abs(-3)
sqrt(17) / 2
exp(3)
log(3)
log(exp(3))
exp(log(3))
```

- R has many built-in mathematical functions that facilitate calculations and data analysis.

:::


::: {.column width="50%"}
- `abs(x)`: the absolute value $|x|$ 
- `sqrt(x)`: the square root $\sqrt{x}$
- `exp(x)`: the exponential value $e^x$, where $e = 2.718...$
- `log(x)`: the natural logarithm $\log_{e}(x)$, or simply $\log(x)$

:::

::::



:::
:::



## R Basics
### Vectorized Operations

```{.r}
a <- c(1, 2, 3, 4, 5)
b <- c(5, 4, 3, 2, 1)

a + b
a - b
a * b
a / b
sqrt(a)
```

- Vectorized operations mean applying a function to every element of a vector without explicitly writing a loop. 
  - This is possible because most functions in R are vectorized, meaning they are designed to operate on vectors element-wise.
  - Vectorized operations are a powerful feature of R, enabling efficient and concise code for data analysis and manipulation.



