---
title: Homework Assignment 3
subtitle: ""
date: last-modified
from: markdown+emoji
comments: false
code-fold: false

execute: 
  warning: false
  message: false
  fig-width: 9
  fig-height: 7
  fig-align: center
  eval: false
---
```{r}
#| include: false
#| eval: true

library(tidyverse)
library(skimr)
library(DT)
library(hrbrthemes)
library(ggthemes)

titanic <- read_csv("https://bcdanl.github.io/data/titanic_cleaned.csv")
oj <- read_csv("https://bcdanl.github.io/data/dominick_oj_na.csv")
mlb_bat <- read_csv("https://bcdanl.github.io/data/MLB_batting.csv")

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))

# Set global options for color-blind-friendly scales
scale_colour_discrete <- function(...) scale_color_colorblind(...)
scale_fill_discrete <- function(...) scale_fill_colorblind(...)

```


- Please answer all of the following questions thoroughly, ensuring that none are left unanswered.
- For Homework Assignment 3, the use of any generative artificial intelligence (AI) tools is strictly prohibited.
- Craft your answers in a separate document (such as an R script, Word file, or Google Doc) and paste them into this page when you are ready to submit.
- Once you have completed the assignment, click the "Submit" button at the bottom of this page to have it evaluated.
  - After clicking **"Submit"** button, wait for the message, **"Data submitted successfully!"**.
  - A **confirmation email** will be sent to the email address that you provide on this homework page once your submission is received.
- You may submit multiple times, but only your most recent submission will be evaluated.
- The due is <u>November 8, 9:30 A.M., 2024, Friday, Eastern Time</u>.



```{=html}
<iframe id="contentFrame" width="100%" height="12000px" frameborder="no"
  src="danl-101-hw-03-google-sheet.html" style="overflow: hidden;">
</iframe>
```


<!-- # Data Transformation and Visualization with R `tidyverse` -->

<!-- The followings are the R packages for this homework assignment: -->
<!-- ```{r} -->
<!-- library(tidyverse) -->
<!-- library(skimr) -->
<!-- ``` -->



<!-- ## Questions 11-12 -->

<!-- Consider the following `oj` data.frame for Questions 11-12: -->

<!-- ```{r} -->
<!-- oj <- read_csv("https://bcdanl.github.io/data/dominick_oj_na.csv") -->
<!-- ``` -->

<!-- ### Question 11 -->
<!-- How can you filter the data.frame `oj` to calculate descriptive statistics (mean and standard deviation) of `sales` and `price` for **tropicana**, **minute.maid**, and **dominicks**, respectively?  -->

<!-- Complete the code by filling in the blanks. -->

<!-- ```{r} -->
<!-- oj_tr <- oj |>  -->
<!--   filter(__BLANK__ "tropicana") -->

<!-- oj_mm <- oj |>  -->
<!--   filter(__BLANK__ "minute.maid") -->

<!-- oj_do <- oj |>  -->
<!--   filter(__BLANK__ "dominicks") -->

<!-- oj_tr_sum <- skim(oj_tr) -->
<!-- oj_mm_sum <- skim(oj_mm) -->
<!-- oj_do_sum <- skim(oj_do) -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Question 12 -->
<!-- How would you create a new data.frame, `oj_no_NA`, in which there is no missing value in `price` and `sales`? -->

<!-- Complete the code by filling in the blanks. -->

<!-- ```{r} -->
<!-- oj_no_NA <- oj |>  -->
<!--   filter(__BLANK__) -->
<!-- ``` -->


<!-- <br> -->

<!-- ### Question 13 -->
<!-- How would you describe how the distribution of `price` varies by `brand`? -->

<!-- Complete the code by filling in the blanks. -->

<!-- ```{r} -->
<!-- ggplot(data = __BLANK 1__,  -->
<!--        mapping = aes(x = __BLANK 2__, -->
<!--                      __BLANK 3__)) + -->
<!--   __BLANK 4__(show.legend = FALSE,  # `show.legend = FALSE` turns off legend -->
<!--               __BLANK 5__ = 40) + -->
<!--   facet_wrap(__BLANK 6__,  -->
<!--              __BLANK 7__ = 1) -->
<!-- ``` -->

<!-- ```{r q13} -->
<!-- #| eval: true -->
<!-- #| echo: false -->
<!-- #| fig-height: 9 -->

<!-- ggplot(data = oj,  -->
<!--        mapping = aes(x = price, -->
<!--                      fill = brand)) + -->
<!--   geom_histogram(show.legend = F, bins = 40) + -->
<!--   facet_wrap(~brand,  -->
<!--              ncol = 1) -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Question 14 -->
<!-- Provide a comment to describe how the distribution of `price` varies by `brand`. -->

<!-- <br> -->

<!-- ### Question 15 -->
<!-- How would you describe how the relationship between (1) the base-10 log of `sales` and (2) the base-10 log of `price` varies by `brand`? -->

<!-- Complete the code by filling in the blanks. -->

<!-- ```{r} -->
<!-- ggplot(data = __BLANK 1__,  -->
<!--        mapping = aes(x = __BLANK 2__, -->
<!--                      y = __BLANK 3__, -->
<!--                      __BLANK 4__ = brand, -->
<!--                      __BLANK 5__ = brand)) + -->
<!--   geom_point(__BLANK 6__ = .1) + -->
<!--   geom_smooth(__BLANK 7__) -->
<!-- ``` -->

<!-- ```{r q15} -->
<!-- #| eval: true -->
<!-- #| echo: false -->
<!-- #| fig-height: 8 -->
<!-- ggplot(data = oj,  -->
<!--        mapping = aes(x = log10(sales), -->
<!--                      y = log10(price), -->
<!--                      color = brand, -->
<!--                      fill = brand)) + -->
<!--   geom_point(alpha = .075) + -->
<!--   geom_smooth(method = "lm") -->
<!-- ``` -->


<!-- <br> -->

<!-- ### Question 16 -->
<!-- - Provide a comment to describe how the relationship between (1) the base-10 log of `sales` and (2) the base-10 log of `price` varies by `brand`? -->

<!-- <br> -->

<!-- ### Question 17 -->
<!-- How would you visualize how the relationship between (1) the base-10 log of `sales` and (2) the base-10 log of `price` varies by `brand` and `ad_status`? -->

<!-- Complete the code by filling in the blanks (BLANKS 1-7 are the same as the ones in **Question 13**). -->

<!-- ```{r} -->
<!-- ggplot(data = __BLANK 1__,  -->
<!--        mapping = aes(x = __BLANK 2__, -->
<!--                      y = __BLANK 3__, -->
<!--                      __BLANK 4__ = brand, -->
<!--                      __BLANK 5__ = brand)) + -->
<!--   geom_point(__BLANK 6__ = .1) + -->
<!--   geom_smooth(__BLANK 7__) + -->
<!--   facet_wrap(__BLANK 8__) -->
<!-- ``` -->

<!-- ```{r q14} -->
<!-- #| eval: true -->
<!-- #| echo: false -->
<!-- #| fig-height: 8 -->
<!-- ggplot(data = oj,  -->
<!--        mapping = aes(x = log10(sales), -->
<!--                      y = log10(price), -->
<!--                      color = brand, -->
<!--                      fill = brand)) + -->
<!--   geom_point(alpha = .075) + -->
<!--   geom_smooth(method = "lm") + -->
<!--   facet_wrap(~ad_status) + -->
<!--   theme(legend.position = "top") -->
<!-- ``` -->

<!-- <br> -->


<!-- ### Question 18 -->
<!-- Provide a comment to describe how the relationship between (1) the base-10 log of `sales` and (2) the base-10 log of `price` varies by `brand` and `ad_status`. -->

<!-- <br> -->




<!-- ## Questions 19-20 -->

<!-- Consider the following `mlb_bat` data.frame for Questions 19-20: -->

<!-- ```{r} -->
<!-- mlb_bat <- read_csv("https://bcdanl.github.io/data/MLB_batting.csv") -->
<!-- ``` -->

<!-- ### Question 19 -->
<!-- How would you describe how the yearly trend of hit percentage for each `hit_type` (e.g., **Single**, **Double**, **Triple**, and **HomeRun**)? -->

<!-- Complete the code by filling in the blanks. -->

<!-- ```{r} -->
<!-- ggplot(data = __BLANK __,  -->
<!--        mapping = aes(x = __BLANK __,  -->
<!--                      y = __BLANK __,  -->
<!--                      color = __BLANK __, -->
<!--                      fill = __BLANK __)) + -->
<!--   __BLANK __() +  -->
<!--   __BLANK __() + -->
<!--   __BLANK __() + -->
<!--   labs(title = "Hits by Type in Major League Baseball", -->
<!--        x = "Major League Baseball Season", -->
<!--        y = "Percentage", -->
<!--        fill = "Hit", -->
<!--        color = "Hit")  # labs() allows for  -->
<!--                        # labeling x, y, color, fill, title, etc. -->
<!-- ``` -->

<!-- ```{r q19} -->
<!-- #| eval: true -->
<!-- #| echo: false -->
<!-- #| fig-height: 8 -->
<!-- ggplot(data = mlb_bat, mapping = aes(x = year,  -->
<!--                      y = percentage,  -->
<!--                      color = hit_type, -->
<!--                      fill = hit_type)) + -->
<!--   geom_line(alpha = .5) +  -->
<!--   geom_point(size = .5, alpha = .5) + -->
<!--   geom_smooth(size = .5) + -->
<!--   labs(title = "Hits by Type in Major League Baseball", -->
<!--        x = "Major League Baseball Season", -->
<!--        y = "Percentage", -->
<!--        fill = "Hit", -->
<!--        color = "Hit") + -->
<!--   scale_x_continuous(breaks = c(1870, 1885, 1900, 1915, 1930, 1945,  -->
<!--                                 1960, 1975, 1990, 2005, 2020 )) +  -->
<!--   scale_y_continuous(breaks = c(0, 25, 50, 75, 100)) + -->
<!--   scale_color_colorblind() + -->
<!--   scale_fill_colorblind() + -->
<!--   theme(legend.position = "top") -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Question 20 -->
<!-- Provide a comment to describe how the yearly trend of hit percentage for each `hit_type` (e.g., **Single**, **Double**, **Triple**, and **HomeRun**). -->

