---
title: Homework Assignment 4
subtitle: ""
date: last-modified
from: markdown+emoji
comments: false
code-fold: false

execute: 
  warning: false
  message: false
  fig-width: 9
  fig-height: 7
  fig-align: center
  eval: false
---


```{r}
#| include: false
#| eval: true

library(tidyverse)
library(skimr)
library(DT)
library(hrbrthemes)
library(ggthemes)
library(gapminder)

titanic <- read_csv("https://bcdanl.github.io/data/titanic_cleaned.csv")
oj <- read_csv("https://bcdanl.github.io/data/dominick_oj_na.csv")
mlb_bat <- read_csv("https://bcdanl.github.io/data/MLB_batting.csv")

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5), angle = 0),
                legend.title = element_text(size=rel(1.25))
                ))

# Set global options for color-blind-friendly scales
scale_colour_discrete <- function(...) scale_color_tableau(...)
scale_fill_discrete <- function(...) scale_fill_tableau(...)

```


- Please answer all of the following questions thoroughly, ensuring that none are left unanswered.
- For Homework Assignment 4, the use of any generative artificial intelligence (AI) tools is strictly prohibited.
- **Craft your answers in a separate document (such as an R script, Word file, or Google Doc) and paste them into this page when you are ready to submit.**
- Once you have completed the assignment, click the "Submit" button at the bottom of this page to have it evaluated.
  - After clicking **"Submit"** button, wait for the message, **"Data submitted successfully!"**.
  - A **confirmation email** will be sent to the email address that you provide on this homework page once your submission is received.
- You may submit multiple times, but only your most recent submission will be evaluated.
- The due is <u>November 16, 5:00 P.M., 2024, Saturday, Eastern Time</u>.

<br>


```{=html}
<iframe id="contentFrame" width="100%" height="15000px" frameborder="no"
  src="danl-101-hw-04-google-sheet.html" style="overflow: hidden;">
</iframe>
```

